export default {
    CHANGE_TEXT_SEARCH: 'hosts/CHANGE_TEXT_SEARCH',
    CHANGE_PAGINATION: 'hosts/CHANGE_PAGINATION',
    SET_DATA_HOSTS: 'hosts/SET_DATA_HOSTS',
    SET_LOADING: 'hosts/SET_LOADING'
}