export default {
    CHANGE_TEXT_SEARCH: 'users/CHANGE_TEXT_SEARCH',
    CHANGE_PAGINATION: 'users/CHANGE_PAGINATION',
    SET_DATA_USERS: 'users/SET_DATA_USERS',
    SET_LOADING: 'users/SET_LOADING'
}