export default {
    CHANGE_TEXT_SEARCH: 'hackathons/CHANGE_TEXT_SEARCH',
    CHANGE_PAGINATION: 'hackathons/CHANGE_PAGINATION',
    SET_DATA_HACKATHONS: 'hackathons/SET_DATA_HACKATHONS',
    SET_LOADING: 'hackathons/SET_LOADING',
    CHANGE_FILTER: 'hackathons/CHANGE_FILTER'
}